
# Introducción {-}

La OMS afirma que “el goce del grado máximo de salud que se pueda lograr es uno de los derechos fundamentales de todo ser humano” y además menciona que el cumplimiento de este derecho “exige un conjunto de criterios sociales que propicien la salud de todas las personas, entre ellos la disponibilidad de servicios de salud, condiciones de trabajo seguras, vivienda adecuada y alimentos nutritivos. Un enfoque de la salud basado en los derechos humanos ofrece estrategias y soluciones que permiten afrontar y corregir las desigualdades, las prácticas discriminatorias y las relaciones de poder injustas que suelen ser aspectos centrales de la inequidad en los resultados sanitarios. Las intervenciones para conseguirlo se rigen por principios y normas rigurosos que incluyen: no discriminación, disponibilidad, accesibilidad, aceptabilidad, calidad, rendición de cuentas y universalidad”. 

En este sentido la Constitución del Ecuador en su artículo 32 también manifiesta que la Salud es un derecho que garantiza el Estado. Así también, la Ordenanza Metropolitana N°. 0494 sancionada el 18 de febrero de 2014 señala en su Artículo 4.- La Salud como un derecho.-“el Distrito Metropolitano de Quito promoverá las condiciones sociales que contribuyan y permitan garantizar a todos los ciudadanos que habitan en el territorio del Distrito, sin discriminación alguna, la plena vigencia y el efectivo goce del derecho a la salud y demás derechos relacionados”; (…) el Artículo 5 establece: “La  Secretaria responsable de la Salud en el Distrito Metropolitano de Quito será la responsable de liderar la gestión integral de salud , así como definir las prioridades de salud para la población del Distrito..” y en el Artículo 15.- Generación de conocimiento.- “El Municipio del Distrito Metropolitano de Quito desarrollará políticas, programas y proyectos relacionados con el análisis situacional de la salud en el Distrito Metropolitano de Quito, que permita la articulación con la planificación, la gestión institucional y con el Sistema nacional de Salud”.

A fin de cumplir con lo dispuesto, la Secretaría de Salud pone a disposición el documento “Diagnóstico de salud del Distrito Metropolitano de Quito 2020”, mismo que permite contar con información que ayudará a definir prioridades en el ámbito de la salud y sus determinantes y la toma de decisiones basada en conocimiento y evidencia. Este documento ha sido elaborado a partir de la recolección de información disponible tanto cuantitativa como cualitativa de las condiciones sociales de salud.

Entre los resultados más relevantes se observa que el Distrito Metropolitano de Quito (DMQ), con cerca de 2.781.641 habitantes para el año 2020, muestra un incremento en las personas adultas y adultas mayores (1), siguiendo la tendencia del país y mundial, experimentando dos grandes transiciones; demográfica, producto de la disminución en las tasas de mortalidad y fecundidad, y epidemiológica con disminución general de problemas infecciosos y carenciales ligados a la pobreza, y un aumento de Enfermedades No Trasmisibles (ENT), asociadas con la mayor edad, cambios en los hábitos de vida y el proceso de urbanización.

Estas dos grandes transiciones dan como resultado que las primeras causas de mortalidad en la población del DMQ sean por ENT, responsables del 70,4% de mortalidad; siendo las enfermedades del sistema cardio circulatorio las primeras causas de muerte junto con las neoplasias malignas. El Diagnóstico de Salud contiene un análisis de los determinantes que inciden sobre la salud de la población del DMQ (socioeconómicos, ambientales), los perfiles de morbilidad y mortalidad, datos relevantes de grupos prioritarios, situación de la oferta de salud, recursos identificados en el DMQ para atención de personas de acuerdo a su prioridad y vulnerabilidad, identificación de amenazas geográficas y principales indicadores de resultados. El documento constituye una herramienta útil como fuente de análisis de información descriptiva que puede contribuir de manera efectiva como parte de los insumos para el proceso de priorización y planificación de intervenciones a nivel sanitario, basada en evidencia, que podría profundizarse mediante procesos de investigación.

